### ISSUE TITLE
Please add support for minions

### ISSUE THREAD

**Issue by justinjk007** [TheBB/spaceline#193]
You told me on reddit adding support to [minions](https://github.com/tarsius/minions) would be not that hard, reading the [wiki ](https://github.com/tarsius/minions/wiki) @tarsius seems to suggest a solution, but I don't know how to go about doing it.

So can you please look into this?

**Comment by TheBB** [comment]
I suppose in principle it would be as simple as this:

- Remove the current content from the `minor-modes` segment and put it in a function, e.g. `spaceline-minor-modes-default`.
- Redefine the `minor-modes` segment as follows

```elisp
(spaceline-define-segment minor-modes
  (if (bound-and-true-p minions-mode)
      (format-mode-line minions-mode-line-modes)
    (spaceline-minor-modes-default)))
```

**Comment by TheBB** [comment]
Note that minions-mode will refuse to turn on unless it can modify `mode-line-format` though. I'm not sure about that decision, it means you need to enable `minions-mode` before enabling spaceline.

**Comment by justinjk007** [comment]
Thank you very much this works perfectly, I also added this ` (spaceline-toggle-major-mode-off)` because minions will show the major-mode anyways , this is what it looks like now

**Comment by TheBB** [comment]
Looks like you forgot to define the function `spaceline-minor-modes-default`.

> Also, Is there a hook that runs after loading spaceline, so I can put this config under minons and add a hook to run it after spaceline ?

No, not at the moment.

**Comment by justinjk007** [comment]
Oh ok, this is good for the time being as my problem is solved. May be you add after spaceline hook :) . Thanks for the help

**Comment by TheBB** [comment]
It's not solved from my POV though, I'll keep this open if you don't mind.

**Comment by justinjk007** [comment]
No problem,

**Comment by justinjk007** [comment]
May be you should add it to minions wiki or I can

**Comment by justinjk007** [comment]
One side effect I found out is that this removes the projectile, project name from the modeline. Any Idea how to get that back?

**Comment by jhenahan** [comment]
Relatedly, support for `keycast`, which operates in a similar fashion. I might spend some time hacking on a fork to see if I can make it compatible with Spaceline.
